# Generated by Django 3.2.7 on 2021-10-04 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Verdict',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
