# Generated by Django 3.2.7 on 2021-10-05 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_verdict'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='img_b64',
            field=models.TextField(blank=True, null=True),
        ),
    ]
