# Generated by Django 3.2.7 on 2021-10-12 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0004_report_img_b64'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='img',
            field=models.ImageField(blank=True, default='reports/index.jpg', null=True, upload_to='feeds/'),
        ),
    ]
