# Generated by Django 3.2.7 on 2021-10-12 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0005_alter_report_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='img',
            field=models.ImageField(blank=True, default='reports/report-default.jpg', null=True, upload_to='reports/'),
        ),
    ]
