# Generated by Django 3.2.7 on 2021-10-12 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0006_alter_report_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='img_b64',
        ),
    ]
