# Generated by Django 3.2.7 on 2021-09-28 16:37

from django.db import migrations, models
import feed.models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='thumbnail',
            field=models.ImageField(blank=True, default='uploads/feed/index.jpg', upload_to=feed.models.get_profile_image_filepath),
        ),
    ]
