# Generated by Django 3.2.7 on 2021-09-28 17:25

from django.db import migrations, models
import feed.models
import functools


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_auto_20210929_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='id',
            field=models.CharField(blank=True, default='20210929-002558', max_length=200, primary_key=True, serialize=False),
        ),
    ]
