# Generated by Django 3.2.7 on 2021-09-28 17:28

from django.db import migrations, models
import feed.models
import functools


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0004_auto_20210929_0025'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='imgpath',
            field=models.CharField(blank=True, default='20210929-002817', max_length=200),
        ),
        migrations.AlterField(
            model_name='feed',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
