# Generated by Django 3.2.7 on 2021-09-28 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0007_auto_20210929_0134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='imgpath',
            field=models.CharField(blank=True, default='20210929-014544', max_length=200),
        ),
    ]
