# Generated by Django 3.2.7 on 2021-10-04 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0011_alter_feed_imgpath'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='imgpath',
            field=models.CharField(blank=True, default='20211004-152213', max_length=200),
        ),
    ]
