# Generated by Django 3.2.7 on 2021-10-05 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0013_auto_20211005_1341'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsCategory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='feed',
            name='imgpath',
            field=models.CharField(blank=True, default='20211005-134303', max_length=200),
        ),
    ]
