# Generated by Django 3.2.7 on 2021-10-05 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0016_auto_20211005_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='img_b64',
            field=models.TextField(blank=True, null=True),
        ),
    ]
