# Generated by Django 3.2.7 on 2021-10-12 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0017_alter_feed_img_b64'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewsCategory',
        ),
        migrations.RemoveField(
            model_name='feed',
            name='img_b64',
        ),
        migrations.AlterField(
            model_name='feed',
            name='thumbnail',
            field=models.ImageField(blank=True, default='feeds/index.jpg', null=True, upload_to='feeds/'),
        ),
    ]
