# Generated by Django 3.2.7 on 2021-10-12 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0018_auto_20211012_1516'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feed',
            name='kategori',
        ),
        migrations.AlterField(
            model_name='feed',
            name='thumbnail',
            field=models.ImageField(blank=True, default='feeds/news-default.jpg', null=True, upload_to='feeds/'),
        ),
    ]
