# Generated by Django 3.2.7 on 2021-10-12 16:41

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0019_auto_20211012_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
    ]
